from math import radians,sin, cos, tan
print('--- EXERCICIO 018 ---')
n1 = float(input('Digite o ângulo que você deseja: '))
n2 = radians(n1)
se = sin (n2)
co = cos(n2)
ta = tan(n2)
print('O ângulo de {} tem o SENO de {:.2f}' .format(n1, se))
print('O ângulo de {} tem o COSSENO de {:.2f}' .format(n1, co))
print('O ângulo de {} tem a TANGENTE de {:.2f}' .format(n1, ta))
