print('--- EXERCICIO 015 --- \n ALUGUEL DE CARROS')
n1 = int(input('Quantos dias alugados? '))
n2 = float(input('Quantos km rodados? '))
m = (n1*60)+(n2*0.15)
print('O total a pagar é de R${:.2f}' .format(m))
